sudo: required
dist: trusty

language: haxe

haxe:
 - "3.4.7"
 - "development"

install:
 - haxelib dev LIBNAME .

script:
 - haxe test.hxml

deploy:
 - provider: script
   haxe: 3.4.7
   script: bash ./release_haxelib.sh $HAXELIB_PWD
   on:
	 tags: true
